
export const ON_FLY_CUTTER_COLLISION_DISK = 'ON_FLY_CUTTER_COLLISION_DISK';
export const ON_FLY_CUTTER_COLLISION_KNIFE = 'ON_FLY_CUTTER_COLLISION_KNIFE';
export const ON_PASS_CHECK_POINT = 'ON_PASS_CHECK_POINT';