export const MY_USER_INFO = 'MY_USER_INFO';
export const USER_MENUS = 'USER_MENUS';
export const TOKEN = 'TOKEN';
/** 用户所需要的计分工具 */
export const USER_SCORING_SELECT_TOOLS = 'USER_SCORING_SELECT_TOOLS';
export const USER_SCORING_SELECT_TOOLS_MAP = 'USER_SCORING_SELECT_TOOLS_MAP';
